[2023-03-14T11:11:11.844+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.wget manual__2023-03-14T11:11:11.042917+00:00 [queued]>
[2023-03-14T11:11:11.853+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.wget manual__2023-03-14T11:11:11.042917+00:00 [queued]>
[2023-03-14T11:11:11.853+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-14T11:11:11.853+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-14T11:11:11.853+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-14T11:11:11.864+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): wget> on 2023-03-14 11:11:11.042917+00:00
[2023-03-14T11:11:11.869+0000] {standard_task_runner.py:55} INFO - Started process 2825 to run task
[2023-03-14T11:11:11.871+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'wget', 'manual__2023-03-14T11:11:11.042917+00:00', '--job-id', '1757', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpdlp2dl8t']
[2023-03-14T11:11:11.871+0000] {standard_task_runner.py:83} INFO - Job 1757: Subtask wget
[2023-03-14T11:11:11.883+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-03-14T11:11:11.926+0000] {task_command.py:388} INFO - Running <TaskInstance: LocalIngestionDag.wget manual__2023-03-14T11:11:11.042917+00:00 [running]> on host 67d5ca07a279
[2023-03-14T11:11:11.986+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=wget
AIRFLOW_CTX_EXECUTION_DATE=2023-03-14T11:11:11.042917+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-14T11:11:11.042917+00:00
[2023-03-14T11:11:11.987+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-14T11:11:11.987+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "echo { execution_data.strftime('%Y-%m') }"]
[2023-03-14T11:11:11.997+0000] {subprocess.py:86} INFO - Output:
[2023-03-14T11:11:12.000+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 0: syntax error near unexpected token `('
[2023-03-14T11:11:12.000+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 0: `echo { execution_data.strftime('%Y-%m') }'
[2023-03-14T11:11:12.000+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-03-14T11:11:12.009+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-03-14T11:11:12.012+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=wget, execution_date=20230314T111111, start_date=20230314T111111, end_date=20230314T111112
[2023-03-14T11:11:12.023+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1757 for task wget (Bash command failed. The command returned a non-zero exit code 1.; 2825)
[2023-03-14T11:11:12.042+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-14T11:11:12.062+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
