[2023-03-14T11:13:47.357+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.wget manual__2023-03-14T11:13:47.046257+00:00 [queued]>
[2023-03-14T11:13:47.365+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.wget manual__2023-03-14T11:13:47.046257+00:00 [queued]>
[2023-03-14T11:13:47.365+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-14T11:13:47.365+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-14T11:13:47.365+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-14T11:13:47.376+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): wget> on 2023-03-14 11:13:47.046257+00:00
[2023-03-14T11:13:47.380+0000] {standard_task_runner.py:55} INFO - Started process 3036 to run task
[2023-03-14T11:13:47.382+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'wget', 'manual__2023-03-14T11:13:47.046257+00:00', '--job-id', '1758', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpk4ea0g0d']
[2023-03-14T11:13:47.383+0000] {standard_task_runner.py:83} INFO - Job 1758: Subtask wget
[2023-03-14T11:13:47.392+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-03-14T11:13:47.432+0000] {task_command.py:388} INFO - Running <TaskInstance: LocalIngestionDag.wget manual__2023-03-14T11:13:47.046257+00:00 [running]> on host 67d5ca07a279
[2023-03-14T11:13:47.506+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=wget
AIRFLOW_CTX_EXECUTION_DATE=2023-03-14T11:13:47.046257+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-14T11:13:47.046257+00:00
[2023-03-14T11:13:47.508+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-14T11:13:47.509+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo { execution_date.strftime("%Y-%m") }']
[2023-03-14T11:13:47.518+0000] {subprocess.py:86} INFO - Output:
[2023-03-14T11:13:47.519+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 0: syntax error near unexpected token `('
[2023-03-14T11:13:47.519+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 0: `echo { execution_date.strftime("%Y-%m") }'
[2023-03-14T11:13:47.519+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-03-14T11:13:47.529+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-03-14T11:13:47.532+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=wget, execution_date=20230314T111347, start_date=20230314T111347, end_date=20230314T111347
[2023-03-14T11:13:47.542+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1758 for task wget (Bash command failed. The command returned a non-zero exit code 1.; 3036)
[2023-03-14T11:13:47.554+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-14T11:13:47.574+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
