[2023-03-17T10:26:31.432+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest manual__2023-03-17T10:26:27.725618+00:00 [queued]>
[2023-03-17T10:26:31.439+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest manual__2023-03-17T10:26:27.725618+00:00 [queued]>
[2023-03-17T10:26:31.439+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-17T10:26:31.439+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-17T10:26:31.439+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-17T10:26:31.452+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): ingest> on 2023-03-17 10:26:27.725618+00:00
[2023-03-17T10:26:31.456+0000] {standard_task_runner.py:55} INFO - Started process 931 to run task
[2023-03-17T10:26:31.458+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'manual__2023-03-17T10:26:27.725618+00:00', '--job-id', '1774', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmp_ze6241c']
[2023-03-17T10:26:31.459+0000] {standard_task_runner.py:83} INFO - Job 1774: Subtask ingest
[2023-03-17T10:26:31.469+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-03-17T10:26:31.506+0000] {task_command.py:388} INFO - Running <TaskInstance: LocalIngestionDag.ingest manual__2023-03-17T10:26:27.725618+00:00 [running]> on host 846854af4045
[2023-03-17T10:26:31.532+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:205: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-03-17T10:26:31.562+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=ingest
AIRFLOW_CTX_EXECUTION_DATE=2023-03-17T10:26:27.725618+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-17T10:26:27.725618+00:00
[2023-03-17T10:26:31.563+0000] {logging_mixin.py:137} INFO - ??? /opt/***/output_2023-03.csv
[2023-03-17T10:26:31.564+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingestion_script.py", line 10, in ingest_callable
    engine = create_engine(f'postgresql://{user}:{password}@{host}:{port}/{db}')
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 518, in create_engine
    u = _url.make_url(url)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 738, in make_url
    return _parse_url(name_or_url)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 794, in _parse_url
    components["port"] = int(components["port"])
ValueError: invalid literal for int() with base 10: 'None'
[2023-03-17T10:26:31.572+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=ingest, execution_date=20230317T102627, start_date=20230317T102631, end_date=20230317T102631
[2023-03-17T10:26:31.585+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1774 for task ingest (invalid literal for int() with base 10: 'None'; 931)
[2023-03-17T10:26:31.629+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-17T10:26:31.642+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
